version: "3.8"

services:
  php_app:
    build: ./php
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    expose:
      - "8080"
    restart: always
    

  flask_app:
    build: ./flask
    ports:
      - "5000:5000"
    expose:
      - "5000"
    restart: always

  fastapi_app:
    build: ./fastapi
    ports:
      - "5001:5001"
    expose:
      - "5001"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php_app
      - flask_app
      - fastapi_app
    restart: always
