version: "3.8"

services:
  php_app:
    image: php:8.2-apache
    volumes:
      - ./php:/var/www/html
    expose:
      - "80"

  flask_app:
    build: ./flask
    expose:
      - "5000"

  fastapi_app:
    build: ./fastapi
    expose:
      - "5001"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php_app
      - flask_app
      - fastapi_app
