version: "3.8"

services:
  php_app:
    build: ./php
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes:
      - ./php:/var/www/html
    restart: always
    networks:
      - system_net

  restaurant_app:
    build: ./restaurant
    ports:
      - "8081:80"
    expose:
      - "80"
    volumes:
      - ./restaurant:/var/www/html
    restart: always
    networks:
      - system_net

  flask_app:
    build: ./flask
    ports:
      - "5000:5000"
    expose:
      - "5000"
    restart: always
    volumes:
      - ./flask:/app
    networks:
      - system_net

  fastapi_app:
    build: ./fastapi
    ports:
      - "5001:5001"
    expose:
      - "5001"
    restart: always
    volumes:
      - ./fastapi:/app
    networks:
      - system_net

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php_app
      - flask_app
      - fastapi_app
      - restaurant_app
    restart: always
    networks:
      - system_net

  db_mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant
      MYSQL_USER: restaurant
      MYSQL_PASSWORD: restaurant
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    expose:
      - "3306"
    restart: always
    networks: 
      - system_net

networks:
  system_net:
