version: "3.8"

services:
  php_app:
    build: ./php
    ports:
      - "8080:80"
    expose:
      - "8080"
    restart: always
    networks:
      - system_net
    

  flask_app:
    build: ./flask
    ports:
      - "5000:5000"
    expose:
      - "5000"
    restart: always
    networks:
      - system_net

  fastapi_app:
    build: ./fastapi
    ports:
      - "5001:5001"
    expose:
      - "5001"
    restart: always
    networks:
      - system_net

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php_app
      - flask_app
      - fastapi_app
    restart: always
    networks:
      - system_net

networks:
  system_net:
